import { StyleSheet } from 'react-native';
import { AppTheme } from '../../../theme/theme';

export const createClaimDetailScreenStyles = (theme: AppTheme) =>
  StyleSheet.create({
    backRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: theme.spacing.lg,
    },
    backText: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      marginLeft: theme.spacing.sm,
      fontWeight: '500',
    },
    headerCard: {
      marginBottom: theme.spacing.xl,
    },
    headerCardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: theme.spacing.lg,
    },
    caseId: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      marginLeft: theme.spacing.md,
      letterSpacing: 0.4,
    },
    elapsed: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      marginLeft: theme.spacing.sm,
    },
    caseTitle: {
      ...theme.typography.h1,
      color: theme.colors.textPrimary,
      fontWeight: '700',
      marginBottom: theme.spacing.sm,
      lineHeight: 34,
    },
    caseSub: {
      ...theme.typography.body,
      color: theme.colors.textTertiary,
      marginBottom: theme.spacing.lg,
    },
    headerCtaRow: {
      flexDirection: 'row',
      marginBottom: theme.spacing.lg,
    },
    headerMetricsGrid: {
      flexDirection: 'row',
      marginBottom: theme.spacing.md,
    },
    metricGap: { width: theme.spacing.md },

    section: { marginBottom: theme.spacing.xl },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    sectionTitle: {
      ...theme.typography.h2,
      color: theme.colors.textPrimary,
      fontWeight: '700',
      marginBottom: theme.spacing.xs,
    },
    sectionMeta: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
    },
    sectionLink: {
      ...theme.typography.bodySmall,
      color: theme.colors.primary,
      fontWeight: '700',
    },
    captureMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: theme.spacing.md,
    },
    captureMeta: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
    },

    summaryBody: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      lineHeight: 22,
      marginTop: theme.spacing.md,
      marginBottom: theme.spacing.lg,
    },
    bold: { fontWeight: '700' },
    tagsCol: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.sm as any,
    },
    summaryTag: {
      marginRight: theme.spacing.sm,
      marginBottom: theme.spacing.sm,
    },

    timelineWrap: { marginTop: theme.spacing.md },
    timelineRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    timelineDotCol: {
      width: 18,
      alignItems: 'center',
    },
    timelineDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
      marginVertical: 4,
    },
    timelineLineTop: {
      width: 1,
      height: 12,
      backgroundColor: theme.colors.divider,
    },
    timelineLineBottom: {
      width: 1,
      flex: 1,
      backgroundColor: theme.colors.divider,
    },
    timelineContent: {
      flex: 1,
      marginLeft: theme.spacing.md,
      marginBottom: theme.spacing.lg,
    },
    timelineWhen: {
      ...theme.typography.eyebrow,
      color: theme.colors.textTertiary,
      marginBottom: 2,
    },
    timelineDesc: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      lineHeight: 22,
    },

    kvList: { marginTop: theme.spacing.md },
    kvRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: theme.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.divider,
    },
    kvLabel: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      flex: 1,
    },
    kvValue: {
      ...theme.typography.bodyStrong,
      color: theme.colors.textPrimary,
      flex: 1.4,
      textAlign: 'right',
    },

    physRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: theme.spacing.md,
    },
    physLeft: { flex: 1 },
    physLabel: {
      ...theme.typography.bodyStrong,
      color: theme.colors.textPrimary,
      marginBottom: 2,
      fontSize: theme.fonts.sizes.lg,
    },
    physBaseline: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
    },
    physValue: {
      ...theme.typography.h2,
      color: theme.colors.textPrimary,
      fontWeight: '700',
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.divider,
    },

    actionPathCard: {
      borderRadius: theme.radii.xxl,
      padding: theme.spacing.xxl,
      marginTop: theme.spacing.md,
      marginBottom: theme.spacing.xl,
    },
    actionEyebrow: {
      ...theme.typography.eyebrow,
      color: theme.colors.textOnDarkSubtle,
      letterSpacing: 1.4,
      marginBottom: theme.spacing.md,
    },
    actionTitle: {
      ...theme.typography.h2,
      color: theme.colors.textOnDark,
      fontWeight: '700',
      marginBottom: theme.spacing.lg,
    },
    actionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.18)',
      borderRadius: theme.radii.xl,
      padding: theme.spacing.lg,
    },
    actionGap: { height: theme.spacing.md },
    actionIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.16)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: theme.spacing.md,
    },
    actionLabel: {
      ...theme.typography.bodyStrong,
      color: theme.colors.textOnDark,
      flex: 1,
      fontSize: theme.fonts.sizes.lg,
    },

    // ── ECG History Table — redesigned ──────────────────────────────────────
   // ── ECG Comparison Table — horizontal (rows = metrics, cols = ECG records) ──
    cmpOuter: {
      marginTop: theme.spacing.md,
      borderRadius: theme.radii.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: 'hidden',
    },
    cmpHeaderRow: {
      flexDirection: 'row',
      backgroundColor: theme.colors.backgroundAlt,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    cmpCornerCell: {
      justifyContent: 'flex-end',
      paddingHorizontal: theme.spacing.sm,
      paddingBottom: theme.spacing.sm,
      paddingTop: theme.spacing.md,
      borderRightWidth: 1,
      borderRightColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundAlt,
    },
    cmpCornerText: {
      ...theme.typography.eyebrow,
      color: theme.colors.textTertiary,
      fontSize: 8,
      letterSpacing: 0.8,
    },
    cmpHeaderCell: {
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      alignItems: 'center',
      borderRightWidth: 1,
      borderRightColor: theme.colors.border,
      gap: 4 as any,
      minHeight: 64,
      justifyContent: 'center',
    },
    cmpHeaderCellActive: {
      backgroundColor: 'rgba(99,102,241,0.07)',
    },
    cmpEcgBadge: {
      paddingHorizontal: 7,
      paddingVertical: 3,
      backgroundColor: theme.colors.backgroundAlt,
      borderRadius: theme.radii.pill,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    cmpEcgBadgeText: {
      ...theme.typography.eyebrow,
      color: theme.colors.textSecondary,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    cmpBaselinePill: {
      paddingHorizontal: 5,
      paddingVertical: 2,
      backgroundColor: 'rgba(99,102,241,0.10)',
      borderRadius: theme.radii.pill,
    },
    cmpBaselinePillText: {
      ...theme.typography.eyebrow,
      color: theme.colors.primary,
      fontSize: 8,
      fontWeight: '600',
    },
    cmpAlertPill: {
      paddingHorizontal: 5,
      paddingVertical: 2,
      backgroundColor: 'rgba(245,158,11,0.12)',
      borderRadius: theme.radii.pill,
    },
    cmpAlertPillText: {
      ...theme.typography.eyebrow,
      color: '#F59E0B',
      fontSize: 8,
      fontWeight: '700',
    },
    cmpRow: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    cmpLabelCell: {
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.md,
      borderRightWidth: 1,
      borderRightColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundAlt,
    },
    cmpLabel: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
      fontWeight: '600',
      fontSize: 10,
    },
    cmpDataCell: {
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: theme.spacing.xs,
      paddingVertical: theme.spacing.md,
      borderRightWidth: 1,
      borderRightColor: theme.colors.border,
    },
    cmpDataCellActive: {
      backgroundColor: 'rgba(99,102,241,0.05)',
    },
    cmpDataValue: {
      ...theme.typography.bodySmall,
      color: theme.colors.textPrimary,
      fontWeight: '600',
      fontSize: 11,
      textAlign: 'center',
    },
    cmpDelta: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      fontSize: 9,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 1,
    },
    cmpStPill: {
      paddingHorizontal: 5,
      paddingVertical: 3,
      borderRadius: theme.radii.md,
      alignItems: 'center',
    },
    cmpStPillText: {
      fontSize: 9,
      fontWeight: '700',
      textAlign: 'center',
    },
    cmpAiDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
    },
    
    ecgTableRow: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
      paddingBottom: theme.spacing.md,
      position: 'relative',
    },
    ecgTableRowActive: {
      backgroundColor: 'rgba(99,102,241,0.05)',
    },
    ecgTableRowFirst: {
      borderTopLeftRadius: theme.radii.xl,
      borderTopRightRadius: theme.radii.xl,
    },
    ecgTableRowLast: {
      borderBottomLeftRadius: theme.radii.xl,
      borderBottomRightRadius: theme.radii.xl,
    },
    ecgTableActiveStrip: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 3,
      backgroundColor: theme.colors.primary,
      borderTopLeftRadius: theme.radii.xl,
      borderBottomLeftRadius: theme.radii.xl,
    },
    ecgRowHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: theme.spacing.md,
      gap: theme.spacing.sm as any,
    },
    ecgRecordBadge: {
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 3,
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radii.pill,
    },
    ecgRecordBadgeText: {
      ...theme.typography.eyebrow,
      color: theme.colors.textOnDark,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 0.6,
    },
    ecgRowDate: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
      fontWeight: '600',
      flex: 1,
    },
    ecgChangeBadges: {
      flexDirection: 'row',
      gap: 4 as any,
    },
    ecgBadgeAmber: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      backgroundColor: 'rgba(245,158,11,0.12)',
      borderRadius: theme.radii.pill,
    },
    ecgBadgeAmberText: {
      ...theme.typography.bodySmall,
      color: '#F59E0B',
      fontWeight: '700',
      fontSize: 9,
    },
    ecgBadgeDanger: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      backgroundColor: 'rgba(239,68,68,0.12)',
      borderRadius: theme.radii.pill,
    },
    ecgBadgeDangerText: {
      ...theme.typography.bodySmall,
      color: theme.colors.danger,
      fontWeight: '700',
      fontSize: 9,
    },
    ecgBadgeBaseline: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      backgroundColor: theme.colors.backgroundAlt,
      borderRadius: theme.radii.pill,
    },
    ecgBadgeBaselineText: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      fontWeight: '600',
      fontSize: 9,
    },
    ecgDetailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: theme.spacing.sm,
      borderTopWidth: 1,
      borderTopColor: theme.colors.divider,
    },
    ecgDetailLabel: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      flex: 1,
    },
    ecgDetailValue: {
      ...theme.typography.bodySmall,
      color: theme.colors.textPrimary,
      fontWeight: '600',
      textAlign: 'right',
      flex: 1.5,
    },
    ecgDiagnosisCell: {
      flex: 1.5,
      alignItems: 'flex-end',
    },
    ecgStPill: {
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 3,
      borderRadius: theme.radii.pill,
    },
    ecgStPillText: {
      ...theme.typography.bodySmall,
      fontWeight: '700',
      fontSize: 10,
    },
    ecgAiRiskCell: {
      flex: 1.5,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 5 as any,
    },
    ecgAiDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
    },
    ecgMetricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.sm as any,
      marginTop: theme.spacing.md,
    },
    ecgMetricCell: {
      flex: 1,
      minWidth: '44%',
      backgroundColor: theme.colors.backgroundAlt,
      borderRadius: theme.radii.lg,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    ecgMetricLabel: {
      ...theme.typography.eyebrow,
      color: theme.colors.textTertiary,
      fontSize: 9,
      letterSpacing: 0.6,
      marginBottom: 2,
    },
    ecgMetricValue: {
      ...theme.typography.h2,
      color: theme.colors.textPrimary,
      fontWeight: '700',
      fontSize: 16,
    },
    ecgMetricUnit: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
      fontWeight: '400',
      fontSize: 10,
    },
    ecgDeltaText: {
      ...theme.typography.bodySmall,
      fontWeight: '700',
      fontSize: 10,
      marginTop: 1,
    },
    ecgRowDivider: {
      height: 1,
      backgroundColor: theme.colors.border,
      marginTop: theme.spacing.md,
      marginHorizontal: -theme.spacing.lg,
    },

    // ── ECG Record Comparison ────────────────────────────────────────────────
    comparisonCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radii.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: theme.spacing.lg,
      overflow: 'hidden',
    },
    comparisonHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    comparisonIndex: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: theme.spacing.md,
    },
    comparisonIndexText: {
      ...theme.typography.bodySmall,
      color: theme.colors.textOnDark,
      fontWeight: '700',
    },
    comparisonRecordName: {
      ...theme.typography.bodyStrong,
      color: theme.colors.textPrimary,
      flex: 1,
      fontWeight: '600',
    },
    comparisonRhythm: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
    },
    comparisonBody: {
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.lg,
    },
    comparisonMetricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.md as any,
      marginBottom: theme.spacing.md,
    },
    comparisonMetricBox: {
      flex: 1,
      minWidth: '45%',
      backgroundColor: theme.colors.backgroundAlt,
      borderRadius: theme.radii.lg,
      padding: theme.spacing.md,
    },
    comparisonMetricLabel: {
      ...theme.typography.eyebrow,
      color: theme.colors.textTertiary,
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    comparisonMetricValue: {
      ...theme.typography.h2,
      color: theme.colors.textPrimary,
      fontWeight: '700',
    },
    comparisonMetricUnit: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
      fontWeight: '400',
    },
    deltaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.backgroundAlt,
      borderRadius: theme.radii.lg,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      marginTop: theme.spacing.sm,
      gap: 6 as any,
    },
    deltaLabel: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      flex: 1,
    },
    deltaValuePositive: {
      ...theme.typography.bodySmall,
      color: theme.colors.danger,
      fontWeight: '700',
    },
    deltaValueNegative: {
      ...theme.typography.bodySmall,
      color: theme.colors.success,
      fontWeight: '700',
    },
    deltaValueNeutral: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    stBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: theme.spacing.md,
      paddingVertical: 4,
      borderRadius: theme.radii.pill,
      marginTop: theme.spacing.sm,
    },
    stBadgeText: {
      ...theme.typography.bodySmall,
      fontWeight: '700',
    },
    aiRiskRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: theme.spacing.sm,
      gap: 8 as any,
    },
    aiRiskDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    aiRiskLabel: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
    },
    changedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4 as any,
      backgroundColor: 'rgba(255,165,0,0.12)',
      borderRadius: theme.radii.pill,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    changedBadgeText: {
      ...theme.typography.bodySmall,
      color: '#F59E0B',
      fontWeight: '600',
      fontSize: 10,
    },

    // ── ECG Timeline Table ──────────────────────────────────────────────────
    timelineTableWrap: {
      borderRadius: theme.radii.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: 'hidden',
      marginTop: theme.spacing.md,
    },
    timelineTableHeader: {
      flexDirection: 'row',
      backgroundColor: theme.colors.backgroundAlt,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    timelineTableHeaderCell: {
      ...theme.typography.eyebrow,
      color: theme.colors.textTertiary,
      fontSize: 9,
      letterSpacing: 0.8,
      textAlign: 'center',
    },
    timelineTableRow: {
      flexDirection: 'row',
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      alignItems: 'center',
    },
    timelineTableRowActive: {
      backgroundColor: 'rgba(99,102,241,0.06)',
    },
    timelineTableCell: {
      ...theme.typography.bodySmall,
      color: theme.colors.textPrimary,
      textAlign: 'center',
      fontWeight: '500',
    },
    timelineTableCellMuted: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      textAlign: 'center',
    },
    timelineDeltaUp: {
      ...theme.typography.bodySmall,
      color: theme.colors.danger,
      fontWeight: '700',
      textAlign: 'center',
    },
    timelineDeltaDown: {
      ...theme.typography.bodySmall,
      color: theme.colors.success,
      fontWeight: '700',
      textAlign: 'center',
    },
    timelineDeltaNeutral: {
      ...theme.typography.bodySmall,
      color: theme.colors.textTertiary,
      textAlign: 'center',
    },
    timelineIndexBadge: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
    },
    timelineIndexText: {
      ...theme.typography.bodySmall,
      color: theme.colors.textOnDark,
      fontWeight: '700',
      fontSize: 10,
    },
    // ── Notes textarea inside ActionPath ───────────────────────────────────
    notesInput: {
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.20)',
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderRadius: theme.radii.xl,
      padding: theme.spacing.md,
      color: '#FFFFFF',
      fontSize: 14,
      minHeight: 80,
      textAlignVertical: 'top',
      marginBottom: theme.spacing.lg,
    },
    // ── Orinn AI risk badge ────────────────────────────────────────────────
    riskBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: theme.radii.pill,
    },
    riskBadgeText: {
      fontSize: 11,
      fontWeight: '700',
    },
    recommendationBox: {
      marginTop: theme.spacing.md,
      backgroundColor: theme.colors.backgroundAlt,
      borderRadius: theme.radii.lg,
      padding: theme.spacing.md,
    },
    recommendationText: {
      ...theme.typography.bodySmall,
      color: theme.colors.textSecondary,
      lineHeight: 20,
    },
  });